version: '3.7'

services:
  es-oss-01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION}
    container_name: elasticsearch-oss
    environment:
      - cluster.name=my_oss
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/${HOME_DIR}/data/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet
  ki-oss-01:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION}
    container_name: kibana-oss
    hostname: kibana
    ports: ['5601:5601']
    networks: ['esnet']
    depends_on: ['es-oss-01']
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=http://es-oss-01:9200

networks:
  esnet:
