version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - cluster.name=test
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "es-data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    networks:
      - esnet
  ki01:
    image: docker.elastic.co/kibana/kibana-oss:${ELASTIC_VERSION}
    container_name: kibana
    hostname: kibana
    ports: ['5601:5601']
    networks: ['esnet']
    depends_on: ['es01']
    #restart: on-failure
    environment:
      - ELASTICSEARCH_URL=http://es01:9200

volumes:
  es-data:

networks:
  esnet:
