version: '3.7'

services:
  es-oss-01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION}
    container_name: elasticsearch-oss
    environment:
      - cluster.name=my_oss
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/${HOME_DIR}/data/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
