version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    hostname: kibana
    ports: ['5601:5601']
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
