version: '3.7'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: es-proseco
    environment:
      - cluster.name=hack-a-lot
      - bootstrap.memory_lock=true
      - node.name=stretch_armstrong
      - node.ml=false
      - xpack.ml.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=${SECURITY_ENABLED}
      - xpack.security.http.ssl.enabled=${SECURITY_ENABLED}
      - xpack.security.transport.ssl.enabled=${SECURITY_ENABLED}
      - xpack.monitoring.enabled=${MONITORING_ENABLED}
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - http.port=9201
      - transport.tcp.port=9301
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/home/tan/hackathon/proseco:/usr/share/elasticsearch/data"
    ports:
      - 9201:9201
      - 9301:9301
    networks:
      - esnet
    restart: always

networks:
  esnet:
